import fs from 'fs';

// 1. add-transaction-dialog.tsx
let f1 = fs.readFileSync('src/components/accounting/add-transaction-dialog.tsx', 'utf8');
f1 = f1.replace('import { useState } from "react";', 'import { useState, useEffect } from "react";');
f1 = f1.replace('import { cn } from "@/lib/utils";', 'import { cn } from "@/lib/utils";\nimport { useBusiness } from "@/contexts/BusinessContext";');
f1 = f1.replace('export function AddTransactionDialog({ type, onSuccess }: AddTransactionDialogProps) {\n    const [open, setOpen] = useState(false);\n    const [submitting, setSubmitting] = useState(false);', `export function AddTransactionDialog({ type, onSuccess }: AddTransactionDialogProps) {\n    const { activeBusiness } = useBusiness();\n    const [open, setOpen] = useState(false);\n    const [submitting, setSubmitting] = useState(false);\n    const [accounts, setAccounts] = useState<any[]>([]);\n\n    useEffect(() => {\n        if (open && activeBusiness) {\n            fetchAccounts();\n        }\n    }, [open, activeBusiness]);\n\n    async function fetchAccounts() {\n        const { data } = await supabase\n            .from("financial_accounts")\n            .select("name")\n            .eq("business_id", activeBusiness?.id)\n            .order("name");\n        if (data) {\n            setAccounts(data);\n        }\n    }`);
f1 = f1.replace('{ACCOUNTS.map((acc) => (\n                                                <SelectItem key={acc} value={acc}>{acc}</SelectItem>\n                                            ))}', '{accounts.map((acc) => (\n                                                <SelectItem key={acc.name} value={acc.name}>{acc.name}</SelectItem>\n                                            ))}');
fs.writeFileSync('src/components/accounting/add-transaction-dialog.tsx', f1);

// 2. transfer-dialog.tsx
let f2 = fs.readFileSync('src/components/accounting/transfer-dialog.tsx', 'utf8');
f2 = f2.replace('import { supabase } from "@/lib/supabase";', 'import { supabase } from "@/lib/supabase";\nimport { useBusiness } from "@/contexts/BusinessContext";\nimport { useEffect } from "react";');
f2 = f2.replace('export function TransferDialog({ onSuccess }: TransferDialogProps) {\n    const [open, setOpen] = useState(false);\n    const [loading, setLoading] = useState(false);', `export function TransferDialog({ onSuccess }: TransferDialogProps) {\n    const { activeBusiness } = useBusiness();\n    const [open, setOpen] = useState(false);\n    const [loading, setLoading] = useState(false);\n    const [accounts, setAccounts] = useState<any[]>([]);\n\n    useEffect(() => {\n        if (open && activeBusiness) {\n            fetchAccounts();\n        }\n    }, [open, activeBusiness]);\n\n    async function fetchAccounts() {\n        const { data } = await supabase\n            .from("financial_accounts")\n            .select("name")\n            .eq("business_id", activeBusiness?.id)\n            .order("name");\n        if (data) {\n            setAccounts(data);\n        }\n    }`);
f2 = f2.replace('{ACCOUNTS.map((acc) => (\n                                        <SelectItem key={acc} value={acc} disabled={acc === toAccount}>\n                                            {acc}\n                                        </SelectItem>\n                                    ))}', '{accounts.map((acc) => (\n                                        <SelectItem key={acc.name} value={acc.name} disabled={acc.name === toAccount}>\n                                            {acc.name}\n                                        </SelectItem>\n                                    ))}');
f2 = f2.replace('{ACCOUNTS.map((acc) => (\n                                        <SelectItem key={acc} value={acc} disabled={acc === fromAccount}>\n                                            {acc}\n                                        </SelectItem>\n                                    ))}', '{accounts.map((acc) => (\n                                        <SelectItem key={acc.name} value={acc.name} disabled={acc.name === fromAccount}>\n                                            {acc.name}\n                                        </SelectItem>\n                                    ))}');
fs.writeFileSync('src/components/accounting/transfer-dialog.tsx', f2);

// 3. accounting/page.tsx
let f3 = fs.readFileSync('src/app/(dashboard)/accounting/page.tsx', 'utf8');
f3 = f3.replace('import { TransferDialog } from "@/components/accounting/transfer-dialog";', 'import { TransferDialog } from "@/components/accounting/transfer-dialog";\nimport { ManageAccountsDialog } from "@/components/accounting/manage-accounts-dialog";');
f3 = f3.replace(/async function fetchBalances\(\) \{\n        \/\/ Fetch aggregated balances directly from Postgres via RPC\n        const \{ data, error \} = await supabase\.rpc\("get_treasury_balances"\);\n        if \(data\) \{\n            const newBalances: Record<string, number> = \{ "Mohamed Adel": 0, "Abdallah Sherif": 0, "Safe": 0 \};\n            data\.forEach\(\(t: any\) => \{\n                if \(!t\.account_name\) return;\n                newBalances\[t\.account_name\] = Number\(t\.balance\) \|\| 0;\n            \}\);\n            setBalances\(newBalances as any\);\n        \}\n    \}/g, `async function fetchBalances() {\n        if (!activeBusiness) return;\n        \n        try {\n            // Fetch the accounts list for this business\n            const { data: accountsData } = await supabase\n                .from("financial_accounts")\n                .select("name")\n                .eq("business_id", activeBusiness.id);\n\n            // Fetch aggregated balances\n            const { data: balancesData } = await supabase\n                .rpc("get_treasury_balances", { p_business_id: activeBusiness.id });\n\n            const newBalances: Record<string, number> = {};\n            \n            // Initialize all accounts to 0\n            if (accountsData) {\n                accountsData.forEach((acc: any) => {\n                    newBalances[acc.name] = 0;\n                });\n            }\n\n            // Populate actual balances\n            if (balancesData) {\n                balancesData.forEach((t: any) => {\n                    if (!t.account_name) return;\n                    newBalances[t.account_name] = Number(t.balance) || 0;\n                });\n            }\n            \n            setBalances(newBalances as any);\n        } catch (error) {\n            console.error("Error fetching balances:", error);\n        }\n    }`);
f3 = f3.replace('<TransferDialog onSuccess={refresh} />\n            </div>', '<TransferDialog onSuccess={refresh} />\n                <ManageAccountsDialog onSuccess={refresh} />\n            </div>');
fs.writeFileSync('src/app/(dashboard)/accounting/page.tsx', f3);
